package com.drew.tools;

import org.junit.Test;

import com.drew.tools.BinaryPropertyListUtil.CMTime;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

/**
 * 
 * @author Bob Johnson
 */
public class BinaryPropertyListUtilTest 
{

	/**
	 * Expected results are based on the "preview" generated by a OS-X "get info", preview property.
	 * 
	 * @throws Exception
	 */
	@Test
	public void testRunTime() throws Exception
	{
		final byte[] bplist = FileUtil.readBytes("Tests/Data/Apple_RunTime.plist");
		
		final CMTime runTime = BinaryPropertyListUtil.parseAsCMTime(bplist);
		
		assertEquals(0, runTime.getEpoch());
		assertEquals(1, runTime.getFlags());
		assertEquals(1000000000L, runTime.getTimeScale());
		assertEquals(186585209314541L, runTime.getValue());
	}

	/**
	 * When presented as XML, the RUN_TIME tag will be contained within a <tt>dict</tt> XML element.
	 * 
	 * @throws Exception
	 */
	@Test
	public void testRunTimeAsXML() throws Exception
	{
        final byte[] bplist = FileUtil.readBytes("Tests/Data/Apple_RunTime.plist");
		final String xml = BinaryPropertyListUtil.parseAsXML(bplist);

		assertTrue(xml.contains("<plist version=\"1.0\"><dict>"));
	}
	
}
